# Generated by Django 5.1 on 2024-11-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
